CLASS zcl_helloworld2 DEFINITION
PUBLIC
FINAL
CREATE PUBLIC .

PUBLIC SECTION.

INTERFACES if_oo_adt_classrun .
PROTECTED SECTION.
PRIVATE SECTION.
ENDCLASS.

CLASS zcl_helloworld2 IMPLEMENTATION.
METHOD if_oo_adt_classrun~main.
out->write( 'HELLO WORLD DEVELOPERS' ).
ENDMETHOD.
ENDCLASS.

